# -*- coding: utf-8 -*-
"""linear_regression_single_variable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccPMubJd1HzkiaEKlzJusbvl1EClPfq0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df= pd.read_csv("/content/drive/MyDrive/datasets/practice/home_price.csv")

df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area (sq feet)')
plt.ylabel('price (USD)')
plt.scatter(df.area,df.price, color='red', marker='+')

reg= linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

reg.predict(np.array([[3300]]))